### ISSUE TITLE
Skeleton Blog site: Sidebar remains empty

### ISSUE THREAD

**Issue by pamtbaau** [pmoreno-rodriguez/future2021#1]
Not sure if I should, but doing it anyway...

I've installed skeleton "Blog Site" and installed both theme Future and Future2001. 
- Sidebar of Future looks ok
- Sidebar of Future2001 is empty.

**Comment by pmoreno-rodriguez** [comment]
Hi.
I've installed the same skeleton "Blog Site" and these are my results:

# With Future theme:

![Screenshot from 2021-11-19 17-07-53](https://user-images.githubusercontent.com/60596353/142655163-45ca6c07-a7aa-4a0e-a6c6-48fda912a46e.png)

# With Future 2021 theme:

![Screenshot from 2021-11-19 17-11-41](https://user-images.githubusercontent.com/60596353/142655241-c4e7b9ec-6a9f-44a5-9934-8907cdb7a897.png)

![Screenshot from 2021-11-19 17-11-26](https://user-images.githubusercontent.com/60596353/142655265-5faac950-cdb9-494b-8147-7edda0d689ef.png)

You may have to save the theme settings for the results to take effect

**Comment by pamtbaau** [comment]
I think providing sensible defaults in */themes/future2021/future.yaml* and demo images/icons showing the potential of the theme, would improve the first impression for users.


**Future after fixing autoescape**
![Untitled](https://user-images.githubusercontent.com/5120011/142661449-53288341-942e-4afb-b070-66649cea0ce3.png)

**Future2021 without saving config in Admin**
I'm just one of those that don't use Admin...
![Untitled2](https://user-images.githubusercontent.com/5120011/142662285-2f5eb57b-daf4-446d-9ec7-9e5d0ea24b98.png)

**Future2021 with saving default config in Admin**
![Untitled3](https://user-images.githubusercontent.com/5120011/142662740-480d3454-69ea-46f6-851c-59d6c4e48236.png)

**Comment by pmoreno-rodriguez** [comment]
I've just uploaded a new yaml file with default options for theme (logo, footer, copyright, etc.)
