### ISSUE TITLE
Pagination: Next/Previous show arrows instead of text when disabled

### ISSUE THREAD

**Issue by pamtbaau** [pmoreno-rodriguez/future2021#2]
![Untitled](https://user-images.githubusercontent.com/5120011/142639936-900744d3-5f14-4f64-add8-14924a97937d.png)

**Comment by pmoreno-rodriguez** [comment]
What does it matter if an arrow or text appears, it is a disabled button. Only an arrow appears in the first or last set of items, in the rest of cases the Previous and Next text does appear.

**Comment by pamtbaau** [comment]
> What does it matter 

Consistency in the UI?

**Comment by pmoreno-rodriguez** [comment]
Fixed pagination.html.twig to show Previous / Next text instead arrows.
